version: '3.3'

services:
  reverse-proxy:
    image: traefik:2.9
    container_name: ocrd-reverse-proxy
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
    ports:
      - "80:80"
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  processing-server:
    container_name: ocrd-processing-server
    build:
      context: https://github.com/OCR-D/core.git
      args:
        BASE_IMAGE: ubuntu:20.04
    ports:
      - 8000:8000
    volumes:
      - "./ocrd-ps-config.yml:/ocrd-ps-config.yml"
      - "$HOME/.ssh/ocrd-self-login.key:/sshkey"
    command: ocrd network processing-server /ocrd-ps-config.yml -a 0.0.0.0:8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.processing-server.rule=PathPrefix(`/`)"

  webapi:
    container_name: ocrd-webapi
    build: https://github.com/OCR-D/ocrd-webapi-implementation.git#v0.12.0
    ports:
      - 8001:8000
    volumes:
      - "/tmp/ocrd-webapi-data:/tmp/ocrd-webapi-data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webapi-workspace.rule=PathPrefix(`/workspace`)"
      - "traefik.http.routers.webapi-workflow.rule=PathPrefix(`/workflow`)"
    environment:
      - OCRD_WEBAPI_SERVER_PATH=http://141.5.109.66
      - OCRD_WEBAPI_BASE_DIR=/tmp/ocrd-webapi-data
      - OCRD_WEBAPI_DB_URL=mongodb://admin:admin@172.17.0.1:27018
      - OCRD_WEBAPI_DB_NAME=ocrd
      - OCRD_WEBAPI_USERNAME={{ webapiuser }}
      - OCRD_WEBAPI_PASSWORD={{ webapipass }}
    user: "1000:1000"

  docs:
    build: https://github.com/joschrew/fastapi-docs-combine.git#main
    ports:
      - "8091:80"
    environment:
      - "COMBINE_URLS=http://webapi:8000/openapi.json http://processing-server:8000/openapi.json"
      - "COMBINE_TITLE=OCR-D processing server & webapi"
      - "COMBINE_IGNORE=/ /stop /discovery"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.my-docs.rule=PathPrefix(`/docs`)"
      - "traefik.http.middlewares.my-replacepath.replacepath.path=/combined_docs"
      - "traefik.http.routers.my-docs.middlewares=my-replacepath"
      - "traefik.http.routers.my-docs2.rule=PathPrefix(`/customdocs`)"

  database:
    image: "mongo"
    container_name: ocrd-mongodb
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=admin"
      - "MONGO_INITDB_ROOT_PASSWORD=admin"
    ports:
      - "27018:27017"
    # possibly add volume mount to preserve data (currently for development I prefer without)

  queue:
    image: rabbitmq:3-management
    environment:
      - "RABBITMQ_DEFAULT_USER=admin"
      - "RABBITMQ_DEFAULT_PASS=admin"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
